/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing;

import javax.swing.UIManager;

/**
 *
 * @author allen
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        plansButton = new javax.swing.JButton();
        friendsButton = new javax.swing.JButton();
        apptButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeText.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        welcomeText.setText("Welcome USER!");

        plansButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        plansButton.setText("View Plan Requests");
        plansButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plansButtonActionPerformed(evt);
            }
        });

        friendsButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        friendsButton.setText("View Friends");
        friendsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendsButtonActionPerformed(evt);
            }
        });

        apptButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        apptButton.setText("View Appointments");
        apptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(plansButton)
                .addGap(18, 18, 18)
                .addComponent(friendsButton)
                .addGap(18, 18, 18)
                .addComponent(apptButton)
                .addGap(99, 99, 99))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(welcomeText)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addComponent(welcomeText)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plansButton)
                    .addComponent(friendsButton)
                    .addComponent(apptButton))
                .addGap(161, 161, 161))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plansButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plansButtonActionPerformed
        // VIEW PLAN REQUESTS
        this.setVisible(false);
        new ViewRequest().setVisible(true);
    }//GEN-LAST:event_plansButtonActionPerformed

    private void apptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apptButtonActionPerformed
        // VIEW APPOINTMENTS
        this.setVisible(false);
        new ViewPlan().setVisible(true);
    }//GEN-LAST:event_apptButtonActionPerformed

    private void friendsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendsButtonActionPerformed
        // VIEW FRIENDS
        this.setVisible(false);
        new Book().setVisible(true);
    }//GEN-LAST:event_friendsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        String str = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
        
        UIManager.setLookAndFeel(str);
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apptButton;
    private javax.swing.JButton friendsButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton plansButton;
    private javax.swing.JLabel welcomeText;
    // End of variables declaration//GEN-END:variables
}
